### ISSUE TITLE
Problems with common/cdefs and common/types

### ISSUE THREAD

**Issue by hnj2** [PSPReverse/libpspproxy#4]
I was not able to find any library the provided the following files:
```
#include <common/cdefs.h>
#include <common/types.h>
```
I'm able to find both files in the `sys/` folder, but changing the include statements accordingly doesn't fix the problem. Instead I get the errors that `true`, `false` and `bool` are undefined.
Is this maybe a problem with the `C/C++` version or so?

**Comment by hnj2** [comment]
These includes are in `psp-proxy-provider-serial.c`.

**Comment by hnj2** [comment]
I found the solution ... there is a submodule now that needs to be checked out.

**Comment by AkechiShiro** [comment]
Could you please precise the needed submodule, I'm hitting this error at the moment, unable to find a way to solve it @hnj2 ?

**Comment by AkechiShiro** [comment]
Never mind, I found out the way to fix it, needed to clone with --recursive-submodules so that the submodule gets included and the builds now works.
